archive_app:
    resource: "@ArchiveAppBundle/Controller/"
    type:     annotation
    prefix:   /

archive_back:
    resource: '@NarmafzamArchiveBundle/Controller/Back'
    type: annotation
    prefix: /back

archive_front:
    resource: '@NarmafzamArchiveBundle/Controller/Front'
    type: annotation
    prefix: /